import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { listVideos } from "@/lib/videos.functions";
import { PageShell } from "@/components/PageShell";
import { parseEpisode, type EpisodeInfo } from "@/lib/series";
import { VideoCard } from "@/components/VideoCard";
import { FolderGit2, Loader2, PlayCircle, ChevronRight, ChevronDown } from "lucide-react";
import { useState, useMemo } from "react";

export const Route = createFileRoute("/courses")({
  component: Courses,
});

type CourseMap = {
  [courseName: string]: {
    modules: {
      [moduleName: string]: (EpisodeInfo & { rawVideo: any })[];
    };
  };
};

function Courses() {
  const _listVideos = useServerFn(listVideos);
  const { data, isLoading } = useQuery({
    queryKey: ["courses:all"],
    queryFn: () => _listVideos({ data: { limit: 10000, sort: "new" } }),
  });

  const courses = useMemo(() => {
    const map: CourseMap = {};
    if (!data) return map;

    for (const v of data) {
      const ep = parseEpisode(v.title);
      if (ep) {
        // Look for "Course Name - Module Name" pattern generated by Google Drive importer
        const parts = ep.series.split(" - ");
        const courseName = parts.length > 1 ? parts[0]!.trim() : ep.series;
        const moduleName = parts.length > 1 ? parts.slice(1).join(" - ").trim() : "Main Course";

        if (!map[courseName]) map[courseName] = { modules: {} };
        if (!map[courseName].modules[moduleName]) map[courseName].modules[moduleName] = [];
        
        map[courseName].modules[moduleName].push({ ...ep, rawVideo: v });
      } else {
        // If it has " - " but didn't parse as an episode, maybe it's just a loose course file
        const parts = v.title.split(" - ");
        if (parts.length > 1) {
          const courseName = parts[0]!.trim();
          const moduleName = "Loose Files";
          if (!map[courseName]) map[courseName] = { modules: {} };
          if (!map[courseName].modules[moduleName]) map[courseName].modules[moduleName] = [];
          
          map[courseName].modules[moduleName].push({
            series: courseName,
            key: courseName.toLowerCase(),
            season: 1,
            episode: map[courseName].modules[moduleName].length + 1,
            label: "Video",
            rawVideo: v
          });
        }
      }
    }

    // Sort episodes within modules
    for (const course of Object.values(map)) {
      for (const mod of Object.values(course.modules)) {
        mod.sort((a, b) => a.episode - b.episode);
      }
    }
    return map;
  }, [data]);

  return (
    <PageShell title="Courses" icon={FolderGit2}>
      <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
        {isLoading ? (
          <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-white/40" /></div>
        ) : Object.keys(courses).length === 0 ? (
          <div className="py-20 text-center text-white/50">
            No courses found. Ensure your folders use the "Course - Module" naming format.
          </div>
        ) : (
          <div className="flex flex-col gap-8">
            {Object.entries(courses).sort((a, b) => a[0].localeCompare(b[0])).map(([courseName, courseData]) => (
              <CourseBlock key={courseName} courseName={courseName} courseData={courseData} />
            ))}
          </div>
        )}
      </div>
    </PageShell>
  );
}

function CourseBlock({ courseName, courseData }: { courseName: string, courseData: any }) {
  const [expanded, setExpanded] = useState(true);
  const modules = Object.entries(courseData.modules).sort((a, b) => a[0].localeCompare(b[0]));
  const totalVideos = modules.reduce((acc, [_, mods]) => acc + (mods as any[]).length, 0);

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] overflow-hidden">
      <button 
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between bg-white/[0.04] p-5 hover:bg-white/[0.08] transition-colors text-left"
      >
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-white">{courseName}</h2>
          <p className="text-sm text-white/50 mt-1">{modules.length} Modules • {totalVideos} Videos</p>
        </div>
        <div className="rounded-full bg-white/10 p-2">
          {expanded ? <ChevronDown className="w-5 h-5 text-white/70" /> : <ChevronRight className="w-5 h-5 text-white/70" />}
        </div>
      </button>

      {expanded && (
        <div className="p-5 flex flex-col gap-6">
          {modules.map(([moduleName, videos]) => (
            <div key={moduleName} className="flex flex-col gap-3">
              <h3 className="text-lg font-semibold text-white/80 flex items-center gap-2 border-b border-white/10 pb-2">
                <PlayCircle className="w-4 h-4 text-red-400" />
                {moduleName}
                <span className="text-xs font-normal text-white/40 ml-2">{(videos as any[]).length} parts</span>
              </h3>
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
                {(videos as any[]).map((v) => (
                  <VideoCard key={v.rawVideo.id} video={v.rawVideo} showBadge={false} hideTitle={false} />
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
