/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicExtTokenRouteImport } from './routes/api/public/ext/token'
import { Route as ApiPublicExtHeartbeatRouteImport } from './routes/api/public/ext/heartbeat'
import { Route as ApiPublicExtExecRouteImport } from './routes/api/public/ext/exec'
import { Route as ApiPublicExtAdminRouteImport } from './routes/api/public/ext/admin'
import { Route as ApiPublicExtActivateRouteImport } from './routes/api/public/ext/activate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtTokenRoute = ApiPublicExtTokenRouteImport.update({
  id: '/api/public/ext/token',
  path: '/api/public/ext/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtHeartbeatRoute = ApiPublicExtHeartbeatRouteImport.update({
  id: '/api/public/ext/heartbeat',
  path: '/api/public/ext/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtExecRoute = ApiPublicExtExecRouteImport.update({
  id: '/api/public/ext/exec',
  path: '/api/public/ext/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtAdminRoute = ApiPublicExtAdminRouteImport.update({
  id: '/api/public/ext/admin',
  path: '/api/public/ext/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtActivateRoute = ApiPublicExtActivateRouteImport.update({
  id: '/api/public/ext/activate',
  path: '/api/public/ext/activate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/ext/activate': typeof ApiPublicExtActivateRoute
  '/api/public/ext/admin': typeof ApiPublicExtAdminRoute
  '/api/public/ext/exec': typeof ApiPublicExtExecRoute
  '/api/public/ext/heartbeat': typeof ApiPublicExtHeartbeatRoute
  '/api/public/ext/token': typeof ApiPublicExtTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/ext/activate': typeof ApiPublicExtActivateRoute
  '/api/public/ext/admin': typeof ApiPublicExtAdminRoute
  '/api/public/ext/exec': typeof ApiPublicExtExecRoute
  '/api/public/ext/heartbeat': typeof ApiPublicExtHeartbeatRoute
  '/api/public/ext/token': typeof ApiPublicExtTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/ext/activate': typeof ApiPublicExtActivateRoute
  '/api/public/ext/admin': typeof ApiPublicExtAdminRoute
  '/api/public/ext/exec': typeof ApiPublicExtExecRoute
  '/api/public/ext/heartbeat': typeof ApiPublicExtHeartbeatRoute
  '/api/public/ext/token': typeof ApiPublicExtTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/ext/activate'
    | '/api/public/ext/admin'
    | '/api/public/ext/exec'
    | '/api/public/ext/heartbeat'
    | '/api/public/ext/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/ext/activate'
    | '/api/public/ext/admin'
    | '/api/public/ext/exec'
    | '/api/public/ext/heartbeat'
    | '/api/public/ext/token'
  id:
    | '__root__'
    | '/'
    | '/api/public/ext/activate'
    | '/api/public/ext/admin'
    | '/api/public/ext/exec'
    | '/api/public/ext/heartbeat'
    | '/api/public/ext/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicExtActivateRoute: typeof ApiPublicExtActivateRoute
  ApiPublicExtAdminRoute: typeof ApiPublicExtAdminRoute
  ApiPublicExtExecRoute: typeof ApiPublicExtExecRoute
  ApiPublicExtHeartbeatRoute: typeof ApiPublicExtHeartbeatRoute
  ApiPublicExtTokenRoute: typeof ApiPublicExtTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/token': {
      id: '/api/public/ext/token'
      path: '/api/public/ext/token'
      fullPath: '/api/public/ext/token'
      preLoaderRoute: typeof ApiPublicExtTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/heartbeat': {
      id: '/api/public/ext/heartbeat'
      path: '/api/public/ext/heartbeat'
      fullPath: '/api/public/ext/heartbeat'
      preLoaderRoute: typeof ApiPublicExtHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/exec': {
      id: '/api/public/ext/exec'
      path: '/api/public/ext/exec'
      fullPath: '/api/public/ext/exec'
      preLoaderRoute: typeof ApiPublicExtExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/admin': {
      id: '/api/public/ext/admin'
      path: '/api/public/ext/admin'
      fullPath: '/api/public/ext/admin'
      preLoaderRoute: typeof ApiPublicExtAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/activate': {
      id: '/api/public/ext/activate'
      path: '/api/public/ext/activate'
      fullPath: '/api/public/ext/activate'
      preLoaderRoute: typeof ApiPublicExtActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicExtActivateRoute: ApiPublicExtActivateRoute,
  ApiPublicExtAdminRoute: ApiPublicExtAdminRoute,
  ApiPublicExtExecRoute: ApiPublicExtExecRoute,
  ApiPublicExtHeartbeatRoute: ApiPublicExtHeartbeatRoute,
  ApiPublicExtTokenRoute: ApiPublicExtTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
