/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as ApiPublicTelegramRouteImport } from './routes/api/public/telegram'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicCronRouteImport } from './routes/api/public/cron'
import { Route as ApiPublicVideosStreamRouteImport } from './routes/api/public/videos/stream'
import { Route as ApiPublicVideosPlaylistRouteImport } from './routes/api/public/videos/playlist'
import { Route as ApiPublicExtTokenRouteImport } from './routes/api/public/ext/token'
import { Route as ApiPublicExtHeartbeatRouteImport } from './routes/api/public/ext/heartbeat'
import { Route as ApiPublicExtExecRouteImport } from './routes/api/public/ext/exec'
import { Route as ApiPublicExtActivateRouteImport } from './routes/api/public/ext/activate'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramRoute = ApiPublicTelegramRouteImport.update({
  id: '/api/public/telegram',
  path: '/api/public/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRoute = ApiPublicCronRouteImport.update({
  id: '/api/public/cron',
  path: '/api/public/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideosStreamRoute = ApiPublicVideosStreamRouteImport.update({
  id: '/api/public/videos/stream',
  path: '/api/public/videos/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideosPlaylistRoute = ApiPublicVideosPlaylistRouteImport.update({
  id: '/api/public/videos/playlist',
  path: '/api/public/videos/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtTokenRoute = ApiPublicExtTokenRouteImport.update({
  id: '/api/public/ext/token',
  path: '/api/public/ext/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtHeartbeatRoute = ApiPublicExtHeartbeatRouteImport.update({
  id: '/api/public/ext/heartbeat',
  path: '/api/public/ext/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtExecRoute = ApiPublicExtExecRouteImport.update({
  id: '/api/public/ext/exec',
  path: '/api/public/ext/exec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtActivateRoute = ApiPublicExtActivateRouteImport.update({
  id: '/api/public/ext/activate',
  path: '/api/public/ext/activate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/uploads': typeof UploadsRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telegram': typeof ApiPublicTelegramRoute
  '/api/public/ext/activate': typeof ApiPublicExtActivateRoute
  '/api/public/ext/exec': typeof ApiPublicExtExecRoute
  '/api/public/ext/heartbeat': typeof ApiPublicExtHeartbeatRoute
  '/api/public/ext/token': typeof ApiPublicExtTokenRoute
  '/api/public/videos/playlist': typeof ApiPublicVideosPlaylistRoute
  '/api/public/videos/stream': typeof ApiPublicVideosStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/uploads': typeof UploadsRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telegram': typeof ApiPublicTelegramRoute
  '/api/public/ext/activate': typeof ApiPublicExtActivateRoute
  '/api/public/ext/exec': typeof ApiPublicExtExecRoute
  '/api/public/ext/heartbeat': typeof ApiPublicExtHeartbeatRoute
  '/api/public/ext/token': typeof ApiPublicExtTokenRoute
  '/api/public/videos/playlist': typeof ApiPublicVideosPlaylistRoute
  '/api/public/videos/stream': typeof ApiPublicVideosStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/uploads': typeof UploadsRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telegram': typeof ApiPublicTelegramRoute
  '/api/public/ext/activate': typeof ApiPublicExtActivateRoute
  '/api/public/ext/exec': typeof ApiPublicExtExecRoute
  '/api/public/ext/heartbeat': typeof ApiPublicExtHeartbeatRoute
  '/api/public/ext/token': typeof ApiPublicExtTokenRoute
  '/api/public/videos/playlist': typeof ApiPublicVideosPlaylistRoute
  '/api/public/videos/stream': typeof ApiPublicVideosStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/library'
    | '/search'
    | '/studio'
    | '/uploads'
    | '/watch/$slug'
    | '/api/public/cron'
    | '/api/public/health'
    | '/api/public/telegram'
    | '/api/public/ext/activate'
    | '/api/public/ext/exec'
    | '/api/public/ext/heartbeat'
    | '/api/public/ext/token'
    | '/api/public/videos/playlist'
    | '/api/public/videos/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/library'
    | '/search'
    | '/studio'
    | '/uploads'
    | '/watch/$slug'
    | '/api/public/cron'
    | '/api/public/health'
    | '/api/public/telegram'
    | '/api/public/ext/activate'
    | '/api/public/ext/exec'
    | '/api/public/ext/heartbeat'
    | '/api/public/ext/token'
    | '/api/public/videos/playlist'
    | '/api/public/videos/stream'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/library'
    | '/search'
    | '/studio'
    | '/uploads'
    | '/watch/$slug'
    | '/api/public/cron'
    | '/api/public/health'
    | '/api/public/telegram'
    | '/api/public/ext/activate'
    | '/api/public/ext/exec'
    | '/api/public/ext/heartbeat'
    | '/api/public/ext/token'
    | '/api/public/videos/playlist'
    | '/api/public/videos/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRoute
  UploadsRoute: typeof UploadsRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiPublicCronRoute: typeof ApiPublicCronRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicTelegramRoute: typeof ApiPublicTelegramRoute
  ApiPublicExtActivateRoute: typeof ApiPublicExtActivateRoute
  ApiPublicExtExecRoute: typeof ApiPublicExtExecRoute
  ApiPublicExtHeartbeatRoute: typeof ApiPublicExtHeartbeatRoute
  ApiPublicExtTokenRoute: typeof ApiPublicExtTokenRoute
  ApiPublicVideosPlaylistRoute: typeof ApiPublicVideosPlaylistRoute
  ApiPublicVideosStreamRoute: typeof ApiPublicVideosStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram': {
      id: '/api/public/telegram'
      path: '/api/public/telegram'
      fullPath: '/api/public/telegram'
      preLoaderRoute: typeof ApiPublicTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron': {
      id: '/api/public/cron'
      path: '/api/public/cron'
      fullPath: '/api/public/cron'
      preLoaderRoute: typeof ApiPublicCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/videos/stream': {
      id: '/api/public/videos/stream'
      path: '/api/public/videos/stream'
      fullPath: '/api/public/videos/stream'
      preLoaderRoute: typeof ApiPublicVideosStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/videos/playlist': {
      id: '/api/public/videos/playlist'
      path: '/api/public/videos/playlist'
      fullPath: '/api/public/videos/playlist'
      preLoaderRoute: typeof ApiPublicVideosPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/token': {
      id: '/api/public/ext/token'
      path: '/api/public/ext/token'
      fullPath: '/api/public/ext/token'
      preLoaderRoute: typeof ApiPublicExtTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/heartbeat': {
      id: '/api/public/ext/heartbeat'
      path: '/api/public/ext/heartbeat'
      fullPath: '/api/public/ext/heartbeat'
      preLoaderRoute: typeof ApiPublicExtHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/exec': {
      id: '/api/public/ext/exec'
      path: '/api/public/ext/exec'
      fullPath: '/api/public/ext/exec'
      preLoaderRoute: typeof ApiPublicExtExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext/activate': {
      id: '/api/public/ext/activate'
      path: '/api/public/ext/activate'
      fullPath: '/api/public/ext/activate'
      preLoaderRoute: typeof ApiPublicExtActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRoute,
  UploadsRoute: UploadsRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiPublicCronRoute: ApiPublicCronRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicTelegramRoute: ApiPublicTelegramRoute,
  ApiPublicExtActivateRoute: ApiPublicExtActivateRoute,
  ApiPublicExtExecRoute: ApiPublicExtExecRoute,
  ApiPublicExtHeartbeatRoute: ApiPublicExtHeartbeatRoute,
  ApiPublicExtTokenRoute: ApiPublicExtTokenRoute,
  ApiPublicVideosPlaylistRoute: ApiPublicVideosPlaylistRoute,
  ApiPublicVideosStreamRoute: ApiPublicVideosStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
